
version: '3.10'

services:
  pyspark:
    build: 
      context: ./pyspark
    image: pyspark
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # This will make all GPUs visible to the container
      - GRANT_SUDO=yes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    user: root
    env_file:
     - .env
    links:
      - postgres
    volumes:
      - ./workspace:/workspace
      - ./data:/data
      - ./models:/models
    expose:
      - "8888"
    ports:
      - "8888:8888"
    

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: project